// Mock data for demonstration purposes
export const mockClients = [
    {
        id: '1',
        name: 'Maria Silva Santos',
        cpf: '123.456.789-00',
        email: 'maria.silva@email.com',
        phone: '(32) 98765-4321',
        whatsapp: '(32) 98765-4321',
        birthDate: '1985-03-15',
        address: 'Rua das Flores, 123',
        city: 'Juiz de Fora',
        state: 'MG',
        casesCount: 2,
        status: 'active',
        photoUrl: null,
    },
    {
        id: '2',
        name: 'João Pedro Oliveira',
        cpf: '987.654.321-00',
        email: 'joao.oliveira@email.com',
        phone: '(32) 99876-5432',
        whatsapp: '(32) 99876-5432',
        birthDate: '1978-07-22',
        address: 'Av. Rio Branco, 456',
        city: 'Juiz de Fora',
        state: 'MG',
        casesCount: 1,
        status: 'active',
        photoUrl: null,
    },
    {
        id: '3',
        name: 'Ana Carolina Mendes',
        cpf: '456.789.123-00',
        email: 'ana.mendes@email.com',
        phone: '(32) 97654-3210',
        whatsapp: '(32) 97654-3210',
        birthDate: '1992-11-08',
        address: 'Rua Halfeld, 789',
        city: 'Juiz de Fora',
        state: 'MG',
        casesCount: 3,
        status: 'active',
        photoUrl: null,
    },
];

export const mockCases = [
    {
        id: '1',
        caseNumber: '0001234-56.2023.8.13.0145',
        clientId: '1',
        clientName: 'Maria Silva Santos',
        type: 'Trabalhista',
        court: 'TRT - 3ª Região',
        opposingParty: 'Empresa XYZ Ltda',
        status: 'active',
        filingDate: '2023-05-10',
        lastUpdate: '2024-01-05',
        responsibleName: 'Dr. Rogério Almeida',
    },
    {
        id: '2',
        caseNumber: '0007890-12.2023.8.13.0145',
        clientId: '2',
        clientName: 'João Pedro Oliveira',
        type: 'Previdenciário',
        court: 'INSS - Juiz de Fora',
        opposingParty: 'INSS',
        status: 'active',
        filingDate: '2023-08-22',
        lastUpdate: '2024-01-08',
        responsibleName: 'Dr. Rogério Almeida',
    },
    {
        id: '3',
        caseNumber: '0005678-90.2024.8.13.0145',
        clientId: '3',
        clientName: 'Ana Carolina Mendes',
        type: 'Cível',
        court: 'Comarca de Juiz de Fora',
        opposingParty: 'Construtora ABC S/A',
        status: 'active',
        filingDate: '2024-01-03',
        lastUpdate: '2024-01-09',
        responsibleName: 'Dr. Rogério Almeida',
    },
];

export const mockDeadlines = [
    {
        id: '1',
        title: 'Contestação - Processo 0001234-56',
        caseNumber: '0001234-56.2023.8.13.0145',
        clientName: 'Maria Silva Santos',
        dueDate: '2024-01-15',
        priority: 'high',
        status: 'pending',
        assignedTo: 'Dr. Rogério Almeida',
    },
    {
        id: '2',
        title: 'Recurso - Processo 0007890-12',
        caseNumber: '0007890-12.2023.8.13.0145',
        clientName: 'João Pedro Oliveira',
        dueDate: '2024-01-12',
        priority: 'urgent',
        status: 'pending',
        assignedTo: 'Dr. Rogério Almeida',
    },
    {
        id: '3',
        title: 'Perícia - Processo 0005678-90',
        caseNumber: '0005678-90.2024.8.13.0145',
        clientName: 'Ana Carolina Mendes',
        dueDate: '2024-01-20',
        priority: 'medium',
        status: 'pending',
        assignedTo: 'Dr. Rogério Almeida',
    },
];

export const mockHearings = [
    {
        id: '1',
        caseNumber: '0001234-56.2023.8.13.0145',
        clientName: 'Maria Silva Santos',
        type: 'Instrução',
        date: '2024-01-25',
        time: '14:00',
        location: 'TRT 3ª Região - Sala 5',
        judge: 'Juiz Dr. Carlos Alberto',
        status: 'scheduled',
    },
    {
        id: '2',
        caseNumber: '0007890-12.2023.8.13.0145',
        clientName: 'João Pedro Oliveira',
        type: 'Conciliação',
        date: '2024-01-18',
        time: '10:30',
        location: 'Agência INSS - Juiz de Fora',
        judge: 'Juiz Dr. Fernando Silva',
        status: 'scheduled',
    },
];

export const mockPublications = [
    {
        id: '1',
        caseNumber: '0001234-56.2023.8.13.0145',
        parties: 'Maria Silva Santos x Empresa XYZ Ltda',
        publicationDate: '2024-01-08',
        deadline: '2024-01-23',
        content: 'Intimação para apresentação de contrarrazões ao recurso ordinário',
        isProcessed: true,
    },
    {
        id: '2',
        caseNumber: '0007890-12.2023.8.13.0145',
        parties: 'João Pedro Oliveira x INSS',
        publicationDate: '2024-01-05',
        deadline: '2024-01-20',
        content: 'Decisão interlocutória determinando realização de perícia médica',
        isProcessed: true,
    },
];

export const mockDocuments = [
    {
        id: '1',
        name: 'RG - Maria Silva Santos',
        clientName: 'Maria Silva Santos',
        type: 'IDENTITY',
        uploadDate: '2023-05-08',
        status: 'validated',
        size: '2.5 MB',
    },
    {
        id: '2',
        name: 'Contracheque Dezembro 2023',
        clientName: 'Maria Silva Santos',
        type: 'PAYCHECK',
        uploadDate: '2024-01-02',
        status: 'extracted',
        size: '1.2 MB',
    },
    {
        id: '3',
        name: 'Carta de Concessão - INSS',
        clientName: 'João Pedro Oliveira',
        type: 'COURT_DOCUMENT',
        uploadDate: '2023-12-15',
        status: 'validated',
        size: '850 KB',
    },
];

export const mockPowerOfAttorneys = [
    {
        id: '1',
        clientName: 'Maria Silva Santos',
        opposingParty: 'Empresa XYZ Ltda',
        generatedDate: '2023-05-09',
        status: 'signed',
    },
    {
        id: '2',
        clientName: 'João Pedro Oliveira',
        opposingParty: 'INSS',
        generatedDate: '2023-08-20',
        status: 'signed',
    },
    {
        id: '3',
        clientName: 'Ana Carolina Mendes',
        opposingParty: 'Construtora ABC S/A',
        generatedDate: '2024-01-02',
        status: 'generated',
    },
];

export const mockWhatsAppMessages = [
    {
        id: '1',
        recipientName: 'Maria Silva Santos',
        recipientPhone: '(32) 98765-4321',
        message: 'Bom dia! Lembramos que sua audiência está agendada para 25/01/2024 às 14h. Por favor, chegue com 30 minutos de antecedência.',
        sentAt: '2024-01-08 09:30',
        status: 'delivered',
    },
    {
        id: '2',
        recipientName: 'João Pedro Oliveira',
        recipientPhone: '(32) 99876-5432',
        message: 'Feliz aniversário! A equipe do escritório Rogério Almeida Advogados deseja um dia repleto de alegrias!',
        sentAt: '2024-01-07 08:00',
        status: 'read',
    },
];

export const mockOfficialGazettes = [
    {
        id: '1',
        editionNumber: '2024-001',
        publicationDate: '2024-01-08',
        fhemigEntriesCount: 3,
        isProcessed: true,
    },
    {
        id: '2',
        editionNumber: '2024-002',
        publicationDate: '2024-01-09',
        fhemigEntriesCount: 5,
        isProcessed: true,
    },
];
